### ISSUE TITLE
ssh into worker nodes?

### ISSUE THREAD

**Issue by sreekanth-bg** [miqdigital/terraform-aws-eks-cluster#5]
Hi, the work ASG has ssh_key_pair cnfigured but I could see any associated SG allowing ssh access. Could you please let me how to connect into worker nodes?

**Comment by nandeeshb09** [comment]
@sreekanth-bg , You mean ssh into worker nodes?
If yes , then you have to use ssh-key pair which you have already created (pem file) to ssh into worker nodes.

**Comment by sreekanth-bg** [comment]
do I need to create a bastion in the public subnet from where the worker nodes can be reached through ssh?

**Comment by nandeeshb09** [comment]
@sreekanth-bg  You need to configure site-site to vpn to connect private worker nodes instead of bastion host.

**Comment by ntantri** [comment]
@sreekanth-bg is this issue still relevant?
