### ISSUE TITLE
How do I add custom labels to worker nodes ?

### ISSUE THREAD

**Issue by d3bt3ch** [miqdigital/terraform-aws-eks-cluster#7]
How do I add custom labels to worker nodes ?

**Comment by nandeeshb09** [comment]
@debjitk you can specify using extra arguments followed by bootstrap.sh script.

like --kubelet-extra-args "--node-labels=app(key)=label-name --register-with-taints=app(key)=label-name:NoExecute

label-name you can specify based on your requirements.
